# Docker-compose file for development only: sets up required services
# currently only postgres; i'll need minio... eventually
services:
  postgres:
    container_name: dotto_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'dotto'
      PGDATA: /data/postgres
      PGPORT: 5999
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PUBLIC_PORT}:5999"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: